### ISSUE TITLE
Remove all in tree Azure code from kubernetes

### ISSUE THREAD

**Issue by dtzar** [kubernetes-sigs/cloud-provider-azure#5190]
#### What would you like to be added:
Remove all code references for Azure in kubernetes/kubernetes and have equivalent functionality in this provider.

#### Why is this needed:
1. all code is managed by this cloud provider and not in both places
2. [reduce binary file size for kubernetes](https://github.com/kubernetes/kubernetes/issues/76506)
3. requirement per the KEP 
4. [in-tree is turned off by default in 1.29](https://kubernetes.io/blog/2023/12/14/cloud-provider-integration-changes/)

I used this script from main branch of kubernetes at the time of this issue creation to produce this list below.

```bash
to_build=$(rg "package main" ./cmd/ | cut -f 1-3 -d '/' | sort | uniq)
go build -a -v $to_build 2>&1 | grep -v k8s.io/ > built.txt
find . -type f -name "*.a" -exec du -h {} \; | grep -v k8s.io/ | sort -h >list.txt
grep -E 'Azure' list.txt
```

5.0K    ./github.com/Azure/azure-sdk-for-go/version.a
4.0K    ./vendor/github.com/Azure/azure-sdk-for-go/version.a
56K     ./github.com/Azure/go-autorest/autorest/to.a
56K     ./vendor/github.com/Azure/go-autorest/autorest/to.a
140K    ./github.com/Azure/go-autorest/tracing.a
140K    ./vendor/github.com/Azure/go-autorest/tracing.a
156K    ./github.com/Azure/go-autorest/autorest/validation.a
156K    ./vendor/github.com/Azure/go-autorest/autorest/validation.a
240K    ./github.com/Azure/go-autorest/autorest/mocks.a
240K    ./github.com/Azure/go-autorest/logger.a
240K    ./vendor/github.com/Azure/go-autorest/autorest/mocks.a
240K    ./vendor/github.com/Azure/go-autorest/logger.a
896K    ./github.com/Azure/go-autorest/autorest/date.a
896K    ./vendor/github.com/Azure/go-autorest/autorest/date.a
920K    ./github.com/Azure/go-autorest/autorest/adal.a
920K    ./vendor/github.com/Azure/go-autorest/autorest/adal.a
1.2M    ./github.com/Azure/go-autorest/autorest/azure.a
1.2M    ./vendor/github.com/Azure/go-autorest/autorest/azure.a
1.7M    ./github.com/Azure/go-autorest/autorest.a
1.7M    ./vendor/github.com/Azure/go-autorest/autorest.a
3.1M    ./github.com/Azure/azure-sdk-for-go/storage.a
3.1M    ./vendor/github.com/Azure/azure-sdk-for-go/storage.a
7.2M    ./github.com/Azure/azure-sdk-for-go/services/containerservice/mgmt/2020-04-01/containerservice.a
7.2M    ./vendor/github.com/Azure/azure-sdk-for-go/services/containerservice/mgmt/2020-04-01/containerservice.a
7.4M    ./github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2017-05-10/resources.a
7.4M    ./vendor/github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2017-05-10/resources.a
9.3M    ./github.com/Azure/azure-sdk-for-go/services/containerregistry/mgmt/2019-05-01/containerregistry.a
9.3M    ./vendor/github.com/Azure/azure-sdk-for-go/services/containerregistry/mgmt/2019-05-01/containerregistry.a
14M     ./github.com/Azure/azure-sdk-for-go/services/storage/mgmt/2019-06-01/storage.a
14M     ./vendor/github.com/Azure/azure-sdk-for-go/services/storage/mgmt/2019-06-01/storage.a
36M     ./github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2019-12-01/compute.a
36M     ./vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2019-12-01/compute.a
87M     ./github.com/Azure/azure-sdk-for-go/services/network/mgmt/2019-06-01/network.a
87M     ./vendor/github.com/Azure/azure-sdk-for-go/services/network/mgmt/2019-06-01/network.a

Let's use this issue as a root issue to burn this list down.

```[tasklist]
### Tasks
- [ ] Azure/azure-sdk-for-go/services/network/mgmt/2019-06-01/network.a
- [ ] Azure/azure-sdk-for-go/services/compute/mgmt/2019-12-01/compute.a
- [ ] Azure/azure-sdk-for-go/services/storage/mgmt/2019-06-01/storage.a
- [ ] ...
```
