### ISSUE TITLE
Security and quality improvement project

### ISSUE THREAD

**Issue by nilo19** [kubernetes-sigs/cloud-provider-azure#6549]
#### What would you like to be added:

Improve security and code quality.

#### Why is this needed:

```[tasklist]
### Tasks
- [ ] https://github.com/kubernetes-sigs/cloud-provider-azure/issues/6486
- [ ] https://github.com/kubernetes-sigs/cloud-provider-azure/issues/5849
- [ ] https://github.com/kubernetes-sigs/cloud-provider-azure/issues/6550
- [ ] https://github.com/kubernetes-sigs/cloud-provider-azure/issues/6551
- [ ] https://github.com/kubernetes-sigs/cloud-provider-azure/issues/6577
- [ ] https://github.com/kubernetes-sigs/cloud-provider-azure/issues/6602
```
